language: python
python:
    - "2.7.13"   # Python 2.7.12  and pip 9.0.1
    - "3.6"      # Python 3.6.0   and pip 9.0.1
    - "nightly"  # Python 3.7.0a0 and pip 9.0.1  # currently points to 3.7-dev
# command to install dependencies
install:
#   - pip install --upgrade pip  # pip 9.0.1
#   - pip --version  # This does not work
#   - pip install -r requirements.txt
    - pip install flake8
# preflight
before_script:
    # E128 continuation line under-indented for visual indent
    # E401 multiple imports on one line -- Sometime key to 10 lines or less
    flake8 . --count --ignore=E128,E401 --max-line-length=127 --statistics  # --exit-zero
# command to run tests
# script: flake8 .  # nosetests
script:
    - chmod +x *.py
    - ./fake_format.py
notifications:
    on_success: change
    on_failure: always
